pkgbot:
  - repo: adsy-testing
    download-delay: 5
    branches:
      - master
      - testing
    packages:
      centos:
        centos7:
          - dist/python-gitlab-pkgbot-*.noarch.rpm
      debian:
        jessie:
          - dist/python-gitlab-pkgbot_*_all.deb
