pkgbot:
  port: 8084
  base-package-path: /var/www/mirror/repo_packages
  public-root: /var/www/mirror/.aptly/public
  pyaptly-config-path: /etc/pyaptly
  package-structure:
    debian:
      jessie: debian/jessie
      wheezy: debian/wheezy
      stretch: debian/stretch
    ubuntu:
      trusty: ubuntu/trusty
      vivid: ubuntu/vivid
      xenial: ubuntu/xenial
    rhel:
      rhel6: redhat/6
      rhel7: redhat/7
    centos:
      centos6: centos/6
      centos7: centos/7
  scripts:
    rpm-sign: /usr/local/bin/rpmsign-nointeractive.sh
  aptly-fifo-queue: /var/run/aptly-spooler/fifo.sock

gitlab:
  url: https://gitlab.example.com
  token: disMammiIschEsToken
